name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#build') }}

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      env: 
        CI: ""
    - run: npm run build --if-present
    - run: npm test
    
#     - name: Deploy to netlify
#       uses: netlify/actions/cli@master
#       env:
#         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#         NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
#       with:
#         args: deploy --dir=build --prod
#         secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
